// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-platform-dimensions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var PRESETS = {
  "ig-square": { platform: "Instagram", label: "Square Post", width: 1080, height: 1080 },
  "ig-portrait": { platform: "Instagram", label: "Portrait Post", width: 1080, height: 1350 },
  "ig-landscape": { platform: "Instagram", label: "Landscape Post", width: 1080, height: 566 },
  "ig-story": { platform: "Instagram", label: "Story / Reel", width: 1080, height: 1920 },
  "fb-post": { platform: "Facebook", label: "Post", width: 1200, height: 630 },
  "fb-cover": { platform: "Facebook", label: "Cover Photo", width: 820, height: 312 },
  "tw-post": { platform: "Twitter / X", label: "Post Image", width: 1600, height: 900 },
  "tw-header": { platform: "Twitter / X", label: "Header", width: 1500, height: 500 },
  "yt-thumb": { platform: "YouTube", label: "Thumbnail", width: 1280, height: 720 },
  "yt-banner": { platform: "YouTube", label: "Channel Banner", width: 2560, height: 1440 },
  "li-post": { platform: "LinkedIn", label: "Post", width: 1200, height: 627 },
  "li-cover": { platform: "LinkedIn", label: "Cover", width: 1584, height: 396 },
  "pin-standard": { platform: "Pinterest", label: "Standard Pin", width: 1e3, height: 1500 },
  "tt-video": { platform: "TikTok", label: "Video Cover", width: 1080, height: 1920 }
};
var get_platform_dimensions_default = defineTool({
  name: "get_platform_dimensions",
  title: "Get platform image dimensions",
  description: "Return the recommended pixel dimensions for a social media image preset (Instagram, Facebook, Twitter/X, YouTube, LinkedIn, Pinterest, TikTok). Use this to tell users what size an image should be for a given platform placement.",
  inputSchema: {
    preset: z.enum([
      "ig-square",
      "ig-portrait",
      "ig-landscape",
      "ig-story",
      "fb-post",
      "fb-cover",
      "tw-post",
      "tw-header",
      "yt-thumb",
      "yt-banner",
      "li-post",
      "li-cover",
      "pin-standard",
      "tt-video"
    ]).describe("Preset ID, e.g. 'ig-story' for Instagram Story/Reel (1080x1920).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ preset }) => {
    const p = PRESETS[preset];
    const text = `${p.platform} \u2014 ${p.label}: ${p.width}\xD7${p.height}px`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { preset, ...p }
    };
  }
});

// src/lib/mcp/tools/list-platform-presets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var PRESETS2 = [
  { preset: "ig-square", platform: "Instagram", label: "Square Post", width: 1080, height: 1080 },
  { preset: "ig-portrait", platform: "Instagram", label: "Portrait Post", width: 1080, height: 1350 },
  { preset: "ig-landscape", platform: "Instagram", label: "Landscape Post", width: 1080, height: 566 },
  { preset: "ig-story", platform: "Instagram", label: "Story / Reel", width: 1080, height: 1920 },
  { preset: "fb-post", platform: "Facebook", label: "Post", width: 1200, height: 630 },
  { preset: "fb-cover", platform: "Facebook", label: "Cover Photo", width: 820, height: 312 },
  { preset: "tw-post", platform: "Twitter / X", label: "Post Image", width: 1600, height: 900 },
  { preset: "tw-header", platform: "Twitter / X", label: "Header", width: 1500, height: 500 },
  { preset: "yt-thumb", platform: "YouTube", label: "Thumbnail", width: 1280, height: 720 },
  { preset: "yt-banner", platform: "YouTube", label: "Channel Banner", width: 2560, height: 1440 },
  { preset: "li-post", platform: "LinkedIn", label: "Post", width: 1200, height: 627 },
  { preset: "li-cover", platform: "LinkedIn", label: "Cover", width: 1584, height: 396 },
  { preset: "pin-standard", platform: "Pinterest", label: "Standard Pin", width: 1e3, height: 1500 },
  { preset: "tt-video", platform: "TikTok", label: "Video Cover", width: 1080, height: 1920 }
];
var list_platform_presets_default = defineTool2({
  name: "list_platform_presets",
  title: "List platform image presets",
  description: "List every supported social media image preset with its platform, label, and pixel dimensions. Use this when the caller wants to browse available sizes or pick the right preset ID.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: PRESETS2.map((p) => `${p.preset} \u2014 ${p.platform} ${p.label} (${p.width}\xD7${p.height})`).join("\n")
      }
    ],
    structuredContent: { presets: PRESETS2 }
  })
});

// src/lib/mcp/tools/generate-hashtags.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var generate_hashtags_default = defineTool3({
  name: "generate_hashtags",
  title: "Generate hashtags",
  description: "Generate a set of relevant, on-trend hashtags for a social media post given a topic/description and target platform. Mixes broad-reach and niche tags.",
  inputSchema: {
    topic: z2.string().min(3).max(500).describe("Topic or post description to generate hashtags for."),
    platform: z2.enum(["instagram", "twitter", "linkedin", "tiktok"]).default("instagram").describe("Target platform. Instagram/TikTok use more hashtags; LinkedIn/Twitter use fewer."),
    count: z2.number().int().min(3).max(30).default(15).describe("How many hashtags to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ topic, platform, count }) => {
    const apiKey = globalThis.Deno?.env?.get?.("OPENROUTER_API_KEY");
    if (!apiKey) {
      return {
        content: [{ type: "text", text: "Hashtag generation is not configured on this server." }],
        isError: true
      };
    }
    const prompt = `Generate exactly ${count} hashtags for a ${platform} post about: "${topic}".
Rules:
- Mix broad-reach and niche tags.
- No spaces, each starts with #.
- Return ONLY the hashtags separated by spaces, no commentary.`;
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "deepseek/deepseek-chat",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7
      })
    });
    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      return {
        content: [{ type: "text", text: `Hashtag service error ${res.status}: ${errText.slice(0, 200)}` }],
        isError: true
      };
    }
    const data = await res.json();
    const raw = data?.choices?.[0]?.message?.content ?? "";
    const tags = Array.from(raw.matchAll(/#[\w\u00C0-\uFFFF]+/g)).map((m) => m[0]).slice(0, count);
    return {
      content: [{ type: "text", text: tags.join(" ") }],
      structuredContent: { platform, count: tags.length, hashtags: tags }
    };
  }
});

// src/lib/mcp/tools/generate-captions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var generate_captions_default = defineTool4({
  name: "generate_captions",
  title: "Generate social media captions",
  description: "Generate 3 caption variations for a social media post from a text description. Supports different tones and target platforms (Instagram, Twitter/X, LinkedIn, TikTok).",
  inputSchema: {
    description: z3.string().min(3).max(1e3).describe("Description of the post/image/content."),
    tone: z3.enum(["engaging", "professional", "casual", "funny", "inspirational"]).default("engaging").describe("Desired tone of the captions."),
    platform: z3.enum(["instagram", "twitter", "linkedin", "tiktok"]).default("instagram").describe("Target platform \u2014 affects length and style.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ description, tone, platform }) => {
    const apiKey = globalThis.Deno?.env?.get?.("OPENROUTER_API_KEY");
    if (!apiKey) {
      return {
        content: [{ type: "text", text: "Caption generation is not configured on this server." }],
        isError: true
      };
    }
    const lengthGuide = {
      instagram: "1-3 sentences, can include emojis",
      twitter: "under 240 characters, punchy",
      linkedin: "2-4 sentences, professional",
      tiktok: "1-2 short lines, playful"
    };
    const prompt = `Write 3 distinct ${tone} captions for a ${platform} post about: "${description}".
Style: ${lengthGuide[platform]}.
Return ONLY the 3 captions, numbered 1., 2., 3., no other commentary.`;
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "deepseek/deepseek-chat",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.8
      })
    });
    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      return {
        content: [{ type: "text", text: `Caption service error ${res.status}: ${errText.slice(0, 200)}` }],
        isError: true
      };
    }
    const data = await res.json();
    const raw = data?.choices?.[0]?.message?.content ?? "";
    const captions = raw.split(/\n+/).map((l) => l.replace(/^\s*\d+[\.\)]\s*/, "").trim()).filter((l) => l.length > 0).slice(0, 3);
    return {
      content: [{ type: "text", text: captions.map((c, i) => `${i + 1}. ${c}`).join("\n\n") }],
      structuredContent: { platform, tone, captions }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "socialtool-mcp",
  title: "SocialTool",
  version: "0.1.0",
  instructions: "Tools from SocialTool, an AI social-media suite. Use `list_platform_presets` and `get_platform_dimensions` for social media image sizes (Instagram, TikTok, LinkedIn, YouTube, etc.). Use `generate_captions` to draft 3 caption variations from a description. Use `generate_hashtags` to produce relevant hashtags for a topic and platform.",
  tools: [
    list_platform_presets_default,
    get_platform_dimensions_default,
    generate_captions_default,
    generate_hashtags_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
